export const IPC_ERROR_CODES = {
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  NOT_GIT_REPO: 'NOT_GIT_REPO',
  EXTERNAL_OPERATION_FAILED: 'EXTERNAL_OPERATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type IpcErrorCode = typeof IPC_ERROR_CODES[keyof typeof IPC_ERROR_CODES]
